feat(builder): WIP Builder re-implemented in go.
This is a rewrite of builder, moving from all Bash to mostly Go
with just a bit of Bash. See issue #3836.

diff --git a/builder/rootfs/bin/boot b/builder/rootfs/bin/boot
--- a/builder/rootfs/bin/boot
+++ b/builder/rootfs/bin/boot
@@ -20,39 +20,41 @@ export ETCD_PATH=${ETCD_PATH:-/deis/builder}
 export ETCD_TTL=${ETCD_TTL:-20}
 
 # wait for etcd to be available
-until etcdctl --no-sync -C $ETCD ls >/dev/null 2>&1; do
-	echo "waiting for etcd at $ETCD..."
-	sleep $(($ETCD_TTL/2))  # sleep for half the TTL
-done
+#until etcdctl --no-sync -C $ETCD ls >/dev/null 2>&1; do
+	#echo "waiting for etcd at $ETCD..."
+	#sleep $(($ETCD_TTL/2))  # sleep for half the TTL
+#done
 
-# wait until etcd has discarded potentially stale values
-sleep $(($ETCD_TTL+1))
+## wait until etcd has discarded potentially stale values
+#sleep $(($ETCD_TTL+1))
 
-function etcd_safe_mkdir {
-	set +e
-	ERROR="$(etcdctl --no-sync -C $ETCD mkdir $1 2>&1 >/dev/null)"
-	if [[ $? -ne 0 && $(echo $ERROR | grep -ive "key already exists") ]]; then
-		echo "etcd_safe_mkdir: an etcd error occurred ($ERROR)"
-		echo "aborting..."
-		exit 1
-	fi
-	set -e
-}
+#function etcd_safe_mkdir {
+	#set +e
+	#ERROR="$(etcdctl --no-sync -C $ETCD mkdir $1 2>&1 >/dev/null)"
+	#if [[ $? -ne 0 && $(echo $ERROR | grep -ive "key already exists") ]]; then
+		#echo "etcd_safe_mkdir: an etcd error occurred ($ERROR)"
+		#echo "aborting..."
+		#exit 1
+	#fi
+	#set -e
+#}
 
-etcd_safe_mkdir $ETCD_PATH/users
+#etcd_safe_mkdir $ETCD_PATH/users
 
 # wait for confd to run once and install initial templates
-until confd -onetime -node $ETCD --log-level error; do
-	echo "builder: waiting for confd to write initial templates..."
-	sleep $(($ETCD_TTL/2))  # sleep for half the TTL
-done
+#until confd -onetime -node $ETCD --log-level error; do
+	#echo "builder: waiting for confd to write initial templates..."
+	#sleep $(($ETCD_TTL/2))  # sleep for half the TTL
+#done
 
-# spawn confd in the background to update services based on etcd changes
-confd -node $ETCD --log-level error --interval 5 &
-CONFD_PID=$!
+## spawn confd in the background to update services based on etcd changes
+#confd -node $ETCD --log-level error --interval 5 &
+#CONFD_PID=$!
 
-# remove any pre-existing docker.sock
-test -e /var/run/docker.sock && rm -f /var/run/docker.sock
+## remove any pre-existing docker.sock
+#test -e /var/run/docker.sock && rm -f /var/run/docker.sock
+
+builder boot
 
 # force overlayfs if the Docker daemon on the host is using it
 mkdir --parents --mode=0700 /
